$FONT_COLOR = rgb(205, 214, 244)

general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor = eDP-1
    path = /home/thibi/Wallpapers/canvacatppuccinmysticalforest.png
    blur_passes = 2
    blur_size = 2
}

label {
    monitor = eDP-1
    text = $TIME
    color = $FONT_COLOR
    font_size = 96
    font_family = MeowSans Nerd Font Mono Propo
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor = eDP-1
    size = 300, 50
    outline_thickness = 3
    outer_color = rgb(137, 180, 250)
    inner_color = rgb(30, 30, 46)
    font_color = $FONT_COLOR
    font_family = MeowSans Nerd Font Mono Propo
    position = 0, -100
    halign = center
    valign = center
    hide_input = false
    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgb(17, 17, 27)
    shadow_boost = 1.4
}
