
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $terminal
exec-once = nm-applet
exec-once = qs
exec-once = swaync
exec-once = batterywarnings
exec-once = timedatectl set-ntp true
exec-once = hypridle
exec-once = hyprctl setcursor Sim1e-Catppuccin-Mocha 30
exec-once = hyprpaper
