-- Generated by hyprconf2lua v1.3.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:










-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("local_var_terminal")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("qs")
    hl.exec_cmd("swaync")
    hl.exec_cmd("batterywarnings")
    hl.exec_cmd("timedatectl set-ntp true")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprctl setcursor Sim1e-Catppuccin-Mocha 30")
    hl.exec_cmd("hyprpaper")
end)
